// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.1
// source: rpc_create_sweat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSweatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CreateSweatRequest) Reset() {
	*x = CreateSweatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_sweat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSweatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSweatRequest) ProtoMessage() {}

func (x *CreateSweatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_sweat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSweatRequest.ProtoReflect.Descriptor instead.
func (*CreateSweatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_sweat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSweatRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CreateSweatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CreateSweatResponse) Reset() {
	*x = CreateSweatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_sweat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSweatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSweatResponse) ProtoMessage() {}

func (x *CreateSweatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_sweat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSweatResponse.ProtoReflect.Descriptor instead.
func (*CreateSweatResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_sweat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSweatResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_rpc_create_sweat_proto protoreflect.FileDescriptor

var file_rpc_create_sweat_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x77, 0x65,
	0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x28, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x77, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x32, 0x85, 0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a,
	0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06,
	0x53, 0x61, 0x79, 0x42, 0x79, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x77, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x77, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x77, 0x65,
	0x61, 0x74, 0x2d, 0x64, 0x62, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_sweat_proto_rawDescOnce sync.Once
	file_rpc_create_sweat_proto_rawDescData = file_rpc_create_sweat_proto_rawDesc
)

func file_rpc_create_sweat_proto_rawDescGZIP() []byte {
	file_rpc_create_sweat_proto_rawDescOnce.Do(func() {
		file_rpc_create_sweat_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_sweat_proto_rawDescData)
	})
	return file_rpc_create_sweat_proto_rawDescData
}

var file_rpc_create_sweat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_sweat_proto_goTypes = []interface{}{
	(*CreateSweatRequest)(nil),  // 0: pb.CreateSweatRequest
	(*CreateSweatResponse)(nil), // 1: pb.CreateSweatResponse
}
var file_rpc_create_sweat_proto_depIdxs = []int32{
	0, // 0: pb.Greeter.SayHello:input_type -> pb.CreateSweatRequest
	0, // 1: pb.Greeter.SayBye:input_type -> pb.CreateSweatRequest
	1, // 2: pb.Greeter.SayHello:output_type -> pb.CreateSweatResponse
	1, // 3: pb.Greeter.SayBye:output_type -> pb.CreateSweatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_create_sweat_proto_init() }
func file_rpc_create_sweat_proto_init() {
	if File_rpc_create_sweat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_sweat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSweatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_sweat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSweatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_sweat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_create_sweat_proto_goTypes,
		DependencyIndexes: file_rpc_create_sweat_proto_depIdxs,
		MessageInfos:      file_rpc_create_sweat_proto_msgTypes,
	}.Build()
	File_rpc_create_sweat_proto = out.File
	file_rpc_create_sweat_proto_rawDesc = nil
	file_rpc_create_sweat_proto_goTypes = nil
	file_rpc_create_sweat_proto_depIdxs = nil
}
